[tool.ruff.lint]
ignore = [
    # Ignore some rules, since they require a lot of reformatting
    "ANN", "D", "PTH123", "PTH100", "PT009", "N802", "E501",
    "G004", # Logging with f-strings is fine
    "BLE001" # We want to be able to catch-all

]
select = ["ALL"]

[tool.ruff.lint.isort]
force-sort-within-sections = true
split-on-trailing-comma = false
combine-as-imports = true

[tool.ruff.lint.mccabe]
max-complexity = 25

